# Построение confusion matrix
cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

# Визуализация метрик
def plot_metrics(metrics, title):
    plt.figure(figsize=(15, 6))
    plt.bar(class_names, metrics)
    plt.title(title)
    plt.xticks(rotation=45)
    plt.ylim(0, 1)
    plt.grid(ls=':',alpha=.5)
    plt.show()

plot_metrics(precision, 'Precision per Class')
plot_metrics(recall, 'Recall per Class')
plot_metrics(f1, 'F1 Score per Class')

fig = plt.figure(figsize=(15,10), dpi = 200)
ax1 = fig.add_subplot(111)
ax1.plot(Epoch_loss_train_list, color = 'b', label = 'Loss train')
ax1.plot(Epoch_loss_val_list, linestyle='--', color = 'b' , label = 'Loss val' )
ax1.set_ylim(0,3)
ax1.set_title('Loss', size = 15)
ax1.set_xlabel('Epoch', size = 15)
ax1.set_ylabel('c.u.', size = 15)
ax1.legend(fontsize='x-large')
ax1.grid()
plt.show()

fig = plt.figure(figsize=(15,10), dpi = 200)
ax1 = fig.add_subplot(111)
ax1.plot(Epoch_acc_train_list, color = 'k', label = 'Accuracy train')
ax1.plot(Epoch_acc_val_list, linestyle='--', color = 'k', label = 'Accuracy val')
ax1.set_title('Accuracy', size = 15)
ax1.set_xlabel('Epoch', size = 15)
ax1.set_ylabel('c.u.', size = 15)
ax1.set_ylim(0,1)
ax1.legend(fontsize='x-large')
ax1.grid()
plt.show()

fig = plt.figure(figsize=(15,10), dpi = 200)
ax1 = fig.add_subplot(111)
ax1.plot(Precision_train_list, color = 'y', label ='Precision train')
ax1.plot(Precision_val_list, linestyle='--', color = 'y', label ='Precision val')
ax1.set_title('Precision', size = 15)
ax1.set_xlabel('Epoch', size = 15)
ax1.set_ylabel('c.u.', size = 15)
ax1.set_ylim(0,1)
ax1.legend(fontsize='x-large')
ax1.grid()
plt.show()

fig = plt.figure(figsize=(15,10), dpi = 200)
ax1 = fig.add_subplot(111)
ax1.plot(Recall_train_list, color = 'r', label = 'Recall train')
ax1.plot(Recall_val_list, linestyle='--', color = 'r', label = 'Recall val')
ax1.set_title('Recall', size = 15)
ax1.set_xlabel('Epoch', size = 15)
ax1.set_ylabel('c.u.', size = 15)
ax1.set_ylim(0,1)
ax1.legend(fontsize='x-large')
ax1.grid()
plt.show()

fig = plt.figure(figsize=(15,10), dpi = 200)
ax1 = fig.add_subplot(111)
ax1.plot(F1_train_list, color = 'g', label = 'F1 train')
ax1.plot(F1_val_list, linestyle='--', color = 'g', label = 'F1 val')
ax1.set_title('F1', size = 15)
ax1.set_xlabel('Epoch', size = 15)
ax1.set_ylabel('c.u.', size = 15)
ax1.set_ylim(0,1)
ax1.legend(fontsize='x-large')
ax1.grid()
plt.show()
